CREATE DATABASE COLLAGE;
USE COLLAGE;

CREATE TABLE STUDENT (
ROLLNO INT PRIMARY KEY,
NAME VARCHAR(50),
MARKS INT NOT NULL,
GRADE VARCHAR(1),
CITY VARCHAR(20)
);

INSERT INTO STUDENT
(ROLLNO, NAME, MARKS, GRADE, CITY)
VALUES
(101, "RAZZ", 75, "A", "SATNA"),
(102, "PRACHI", 79, "A", "BHOPAL"),
(103, "ARUNENDRA", 52, "B", "INDORE"),
(104, "ANURAG", 77, "C", "JHASI"),
(105, "DAJU", 28, "D", "CHITRAKOOT");

 SELECT *
 FROM STUDENT;
 
 ALTER TABLE STUDENT      #ADD COLUMN
 ADD COLUMN AGE INT;

ALTER TABLE STUDENT 
DROP COLUMN AGE;         #DROP COLUMN

ALTER TABLE STUDENT
RENAME TO STUDENT;

ALTER TABLE BACCHE
CHANGE COLUMN NAAM NAME VARCHAR(50);



ALTER TABLE STUDENT                         #ADD COLUMN
ADD COLUMN STU_AGE INT NOT NULL  DEFAULT 21;

ALTER TABLE STUDENT 
MODIFY AGE VARCHAR(3);

SELECT *
 FROM STUDENT;
 
 ALTER TABLE STUDENT
 CHANGE AGE STU_AGE INT;
 
 ALTER TABLE STUDENT
 DROP COLUMN AGE;
 
 INSERT INTO STUDENT
(ROLLNO, NAME, MARKS, GRADE, CITY, STU_AGE)
VALUES                                          #ADD DETAILS
(106, "GARGI", 90, "A", "GUDGAO", 32);

TRUNCATE TABLE STUDENT;